pipeline {
    agent { node { label 'AGENT-1' } }
    options {
        ansiColor('xterm')
    }
    stages {
        stage('init') {
            steps {
                sh '''
                    ls -ltr
                    pwd
                    cd 1-vpc
                    terraform init
                '''
                
            }
        }
        stage('plan') {
            steps {
                sh '''
                    ls -ltr
                    pwd
                    cd 1-vpc
                    terraform plan
                '''
            }
        }
        stage(Approve){
            steps{
                input "Shell I Apply"
            }
        }
        stage('apply') {
            steps {
                sh ''' 
                ls -ltr
                pwd
                cd 1-vpc
                terraform apply -auto-approve
                
                '''
            }
        }
    }
    post {
        always{
            echo "I will Always run"
        }
        success {
            echo "I will run only Success"
        }
        failure {
            echo "I will run only failure"
        }
    }
}